name: 'Jenkins Job Trigger and Monitor'
description: 'A Github Action to trigger Jenkins jobs and monitor for completion'
inputs:
  jenkins_url:
    description: 'Jenkins URL including http/https protocol'
    required: true
  api_token:
    description: 'The token for authenticating with the Jenkins generic webhook'
    required: true
  job_name:
    description: 'The job name to trigger in Jenkins'
    required: true
  job_params:
    description: 'Job parameters, separated by a comma, to provide to a Jenkins workflow, e.g. "GIT_REPO_URL=https://github.com/lewijacn/opensearch-migrations.git,GIT_BRANCH=main". Job name will automatically be added as a parameter.'
    required: false
    default: ""
  job_timeout_minutes:
    description: 'Max time (minutes) this Github Action will wait for completion'
    required: false
    default: "60"
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies for python webhook
      run: |
        cd webhook-trigger
        python3 -m pip install --upgrade pipenv
        pipenv install --deploy
      shell: bash
    - name: Trigger jenkins job and wait for completion
      run: |
        cd webhook-trigger
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          branch_name="${{ github.event.pull_request.head.ref }}"
          pr_repo_url="https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git"
        else
          branch_name="${{ github.ref_name }}"
          pr_repo_url="https://github.com/${{ github.repository }}.git"
        fi
        echo "Running jenkins test on repo: $pr_repo_url and branch: $branch_name"
        pipenv run python3 default_webhook_trigger.py \
          --jenkins_url="${{ inputs.jenkins_url }}" \
          --pipeline_token="${{ inputs.api_token }}" \
          --job_name="${{ inputs.job_name }}" \
          --job_params="${{ inputs.job_params }}"
          --job_timeout_minutes="${{ inputs.job_timeout_minutes }}"
      shell: bash
branding:
  icon: 'check-circle'
  color: 'green'
