name: Jenkins Trigger CI
on: [push]
jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Action
        id: get_square
        uses: ./ # Uses an action in the root directory
        with:
          jenkins_url: 'https://test-jenkins-url'
          job_name: 'test-job'
          api_token: "${{ secrets.WEBHOOK_TOKEN }}"
          job_param: "STAGE=dev"
          job_timeout_minutes: '2'
